version: 2

registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.GH_PKG_REGISTRY_TOKEN}}

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: wednesday
      time: "00:00"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: wednesday
      time: "00:00"

    # Ensure the new version is stored in `package.json`
    versioning-strategy: increase

    groups:
      # Create dedicated (grouped) PRs for Next.js/trpc/prisma dependencies
      next:
        patterns:
          - "next"
          - "@next/*"
      trpc:
        patterns:
          - "@trpc/*"
          - "@tanstack/react-query"
      prisma:
        patterns:
          - "prisma"
          - "@prisma/*"

      # Update `dependencies` and `devDependencies` separately
      # Create grouped PRs for minor/patch updates
      # Major version updates will get individual PRs
      production:
        dependency-type: production
        update-types:
          - patch
          - minor
      development:
        dependency-type: development
        update-types:
          - patch
          - minor
          
    ignore:
      # Manually update major versions of `@types/node` with the version specified within .nvmrc
      - dependency-name: "@types/node"
        update-types:
          - version-update:semver-major

      # Alveus.gg packages will be updated below from GitHub Package Registry
      - dependency-name: "@alveusgg/*"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: wednesday
      time: "00:00"

    # Ensure the new version is stored in `package.json`
    versioning-strategy: increase

    # Use GitHub Package Registry for Alveus.gg packages
    registries:
      - npm-github
    allow:
      - dependency-name: "@alveusgg/*"
